### PR TITLE
Forge 1.18.2

### PR DESCRIPTION
**Pull request by CCr4ft3r**
Like last time, I would appreciate if you would accept this pull request and publish the version on CurseForge :)

### CODE REVIEW

**Comment by CCr4ft3r** [comment]
Just one notice: I needed to switch to another config lib for 1.18.2 since MidnightLib is not available for Forge 1.18.2

**Comment by feytox** [comment]
Thank you so much for the next pull request. I will publish the build as soon as possible.

**Comment by feytox** [comment]
The build is published on Modrinth and CurseForge.

**Comment by CCr4ft3r** [comment]
Great - thx 👍

**Pull request merged**
